<?php 

namespace MM\Meros\Services\Contracts;

use Illuminate\Support\Str;

use MM\Meros\Services\Contracts\FeatureDefinition;
use MM\Meros\Services\Contracts\Elements\FieldGroup;
use MM\Meros\Services\Contracts\PostMeta;

use MM\Meros\Facades\PostMetaDefinitions as PostMetaRegister;

class PostType extends FeatureDefinition {
    /**
     * The unique handle for this post type, used for registration and referencing in the system.
     *
     * @var string
     */
    public string $handle = '';

    /**
     * The singular label for the post type.
     *
     * @var string
     */
    protected string $singularLabel = '';

    /**
     * The plural label for the post type.
     *
     * @var string
     */
    protected string $pluralLabel = '';

    /**
     * Arguments to be passed to the register_post_type function when registering this post type.
     *
     * @var array
     */
    protected array $args = [];

    /**
     * Field groups associated with this post type.
     *
     * @var array<FieldGroup>
     */
    protected array $fieldGroups = [];

    /**
     * Post meta definitions associated with this post type.
     *
     * @var string|PostMeta
     */
    protected string|PostMeta $meta = '';

    final public function __construct(
        FeatureProvider $provider,
        array           $props = []
    ) {
        $this->provider = $provider;
        $this->setProps($props);

        if (is_string($this->meta) && !empty($this->meta)) {
            $this->instantiatePostMeta();
        }

        $this->queue();
    }

    /**
     * Queues the post type for registration.
     *
     * @return void
     */
    protected function queue(): void {
        if ($this->queued) {
            return;
        }

        $requiredProps = ['handle', 'singularLabel', 'pluralLabel'];

        foreach ($requiredProps as $prop) {
            if (empty($this->$prop)) {
                return;
            }
        }

        add_action('init', function () {
            register_post_type($this->handle, $this->args);

            if ($this->meta instanceof PostMeta) {
                $key = Str::snake($this->handle) . '_meta';
                $this->meta->queueFromPostType($this, $key, []);
            }
        });

        $this->queued = true;
    }

    /***************************
     * Public Chainable methods
     ***************************/

    /**
     * Sets the post type handle.
     *
     * @param string $handle
     *
     * @return self
     */
    public function handle(string $handle): self {
        $this->handle = Str::slug($handle);
        return $this;
    }

    /**
     * Sets the singular and plural labels for the post type.
     *
     * @param string      $singularLabel The singular label for the post type.
     * @param string|null $pluralLabel   The plural label for the post type. If null, it will be generated by pluralizing the singular label.
     *
     * @return self
     */
    public function label(string $singularLabel, ?string $pluralLabel = null): self {
        $this->singularLabel = $singularLabel;
        $this->pluralLabel   = $pluralLabel ?? Str::plural($singularLabel);

        if (!isset($this->args['labels'])) {
            $this->labels([]); // Initialise default labels if they haven't been set yet
        }

        return $this;
    }

    /**
     * Sets the labels for the post type using an array of label overrides.
     *
     * @param array $labels An associative array of label keys and their corresponding values. 
     *                      Any labels not provided will be generated based on the singular and plural labels.
     * 
     * @return self
     */
    public function labels(array $labels): self {
        $parsedLabels = [
            'name'                      => $labels['name'] ?? $this->pluralLabel,
            'singular_name'             => $labels['singular_name'] ?? $this->singularLabel,
            'add_new'                   => $labels['add_new'] ?? 'Add ' . $this->singularLabel,
            'add_new_item'              => $labels['add_new_item'] ?? 'Add New ' . $this->singularLabel,
            'edit_item'                 => $labels['edit_item'] ?? 'Edit ' . $this->singularLabel,
            'new_item'                  => $labels['new_item'] ?? 'New ' . $this->singularLabel,
            'view_item'                 => $labels['view_item'] ?? 'View ' . $this->singularLabel,
            'view_items'                => $labels['view_items'] ?? 'View ' . $this->pluralLabel,
            'search_items'              => $labels['search_items'] ?? 'Search ' . $this->pluralLabel,
            'not_found'                 => $labels['not_found'] ?? 'No ' . $this->pluralLabel . ' found',
            'not_found_in_trash'        => $labels['not_found_in_trash'] ?? 'No ' . $this->pluralLabel . ' found in Trash',
            'parent_item_colon'         => $labels['parent_item_colon'] ?? 'Parent ' . $this->singularLabel . ':',
            'all_items'                 => $labels['all_items'] ?? 'All ' . $this->pluralLabel,
            'archives'                  => $labels['archives'] ?? $this->singularLabel . ' Archives',
            'attributes'                => $labels['attributes'] ?? $this->singularLabel . ' Attributes',
            'insert_into_item'          => $labels['insert_into_item'] ?? 'Insert into ' . $this->singularLabel,
            'uploaded_to_this_item'     => $labels['uploaded_to_this_item'] ?? 'Uploaded to this ' . $this->singularLabel,
            'featured_image'            => $labels['featured_image'] ?? 'Featured Image',
            'set_featured_image'        => $labels['set_featured_image'] ?? 'Set featured image',
            'remove_featured_image'     => $labels['remove_featured_image'] ?? 'Remove featured image',
            'use_featured_image'        => $labels['use_featured_image'] ?? 'Use as featured image',
            'menu_name'                 => $labels['menu_name'] ?? $this->pluralLabel,
            'filter_items_list'         => $labels['filter_items_list'] ?? 'Filter ' . $this->pluralLabel . ' list',
            'items_list_navigation'     => $labels['items_list_navigation'] ?? $this->pluralLabel . ' list navigation',
            'items_list'                => $labels['items_list'] ?? $this->pluralLabel . ' list',
            'item_published'            => $labels['item_published'] ?? $this->singularLabel . ' published',
            'item_published_privately'  => $labels['item_published_privately'] ?? $this->singularLabel . ' published privately',
            'item_reverted_to_draft'    => $labels['item_reverted_to_draft'] ?? $this->singularLabel . ' reverted to draft',
            'item_scheduled'            => $labels['item_scheduled'] ?? $this->singularLabel . ' scheduled',
            'item_updated'              => $labels['item_updated'] ?? $this->singularLabel . ' updated',
            'item_trashed'              => $labels['item_trashed'] ?? $this->singularLabel . ' trashed',
            'item_link'                 => $labels['item_link'] ?? 'View ' . $this->singularLabel . ' link',
            'item_link_description'     => $labels['item_link_description'] ?? 'A link to a ' . $this->singularLabel,
        ];

        $this->args['labels'] = $parsedLabels;
        return $this;
    }

    /**
     * Sets the description for the post type.
     *
     * @param string $description
     *
     * @return self
     */
    public function description(string $description): self {
        $this->args['description'] = $description;
        return $this;
    }

    /**
     * Sets the post type to be publicly queryable.
     *
     * @return self
     */
    public function public(): self {
        $this->args['public'] = true;
        return $this;
    }

    /**
     * Sets the post type to be not publicly queryable.
     *
     * @return self
     */
    public function private(): self {
        $this->args['public'] = false;
        return $this;
    }

    /**
     * Sets whether the post type is hierarchical (like pages) or flat (like posts).
     *
     * @param bool $hierarchical
     *
     * @return self
     */
    public function hierarchical(bool $hierarchical = true): self {
        $this->args['hierarchical'] = $hierarchical;
        return $this;
    }

    /**
     * Sets whether the post type should be excluded from search results.
     *
     * @param bool $searchable
     *
     * @return self
     */
    public function searchable(bool $searchable = true): self {
        $this->args['exclude_from_search'] = !$searchable;
        return $this;
    }

    /**
     * Sets whether the post type should be publicly queryable.
     *
     * @param bool $queryable
     *
     * @return self
     */
    public function queryable(bool $queryable = true): self {
        $this->args['publicly_queryable'] = $queryable;
        return $this;
    }

    /**
     * Sets whether the post type should be shown in the admin UI.
     *
     * @param bool $showUi
     *
     * @return self
     */
    public function showUi(bool $showUi = true): self {
        $this->args['show_ui'] = $showUi;
        return $this;
    }

    /**
     * Sets whether the post type should be shown in the admin menu.
     *
     * @param bool $showInMenu
     *
     * @return self
     */
    public function showInMenu(bool $showInMenu = true): self {
        $this->args['show_in_menu'] = $showInMenu;
        return $this;
    }

    /**
     * Sets whether the post type should be shown in navigation menus.
     *
     * @param bool $showInNavMenus
     *
     * @return self
     */
    public function showInNavMenus(bool $showInNavMenus = true): self {
        $this->args['show_in_nav_menus'] = $showInNavMenus;
        return $this;
    }

    /**
     * Sets the menu position for the post type in the admin menu.
     *
     * @param int $position The position in the menu order the post type should appear. 
     *                      5 - below Posts, 10 - below Media, 15 - below Links, 20 - below Pages, 25 - below Comments, 60 - below first separator, 65 - below Plugins, 70 - below Users, 75 - below Tools, 80 - below Settings, 100 - below second separator.
     *
     * @return self
     */
    public function menuPosition(int $position): self {
        $this->args['menu_position'] = $position;
        return $this;
    }

    /**
     * Sets the menu icon for the post type in the admin menu.
     *
     * @param string $icon The URL to the icon or a Dashicons class name (e.g. 'dashicons-admin-post').
     *
     * @return self
     */
    public function menuIcon(string $icon): self {
        $this->args['menu_icon'] = $icon;
        return $this;
    }

    /**
     * Sets whether the post type should be shown in the admin bar.
     *
     * @param bool $showInAdminBar
     *
     * @return self
     */
    public function showInAdminBar(bool $showInAdminBar = true): self {
        $this->args['show_in_admin_bar'] = $showInAdminBar;
        return $this;
    }

    /**
     * Sets whether the post type should be available in the REST API.
     *
     * @param bool $showInRest
     *
     * @return self
     */
    public function showInRest(bool|array $showInRest = true): self {
        if (is_array($showInRest)) {
            $this->args['show_in_rest']   = true;
            $this->args['rest_base']      = $showInRest['rest_base'] ?? null;
            $this->args['rest_namespace'] = $showInRest['rest_namespace'] ?? null;

            return $this;
        }

        $this->args['show_in_rest'] = $showInRest;
        return $this;
    }

    /**
     * Sets the REST API base route for the post type.
     *
     * @param string $restBase
     *
     * @return self
     */
    public function restBase(string $restBase): self {
        $this->args['rest_base'] = $restBase;
        return $this;
    }

    /**
     * Sets the REST API namespace for the post type.
     *
     * @param string $restNamespace
     *
     * @return self
     */
    public function restNamespace(string $restNamespace): self {
        $this->args['rest_namespace'] = $restNamespace;
        return $this;
    }

    /**
     * Sets the capability type for the post type, which determines the base capabilities used for permission checks.
     *
     * @param string|array $capabilityType A string or an array of strings representing the capability type(s) for the post type. 
     *                                     If a string is provided, it will be used for both singular and plural capability types. 
     *                                     If an array is provided, it should have 'singular' and 'plural' keys for respective capability types.
     *
     * @return self
     */
    public function capabilityType(string|array $capabilityType): self {
        $this->args['capability_type'] = $capabilityType;
        return $this;
    }

    /**
     * Sets custom capabilities for the post type, allowing for fine-grained control over permissions.
     *
     * @param array $capabilities An associative array of capability keys and their corresponding values. 
     *                            This allows you to define custom capabilities for actions like editing, deleting, and publishing posts of this type.
     *
     * @return self
     */
     public function capabilities(array $capabilities): self {
        $this->args['capabilities'] = $capabilities;
        return $this;
    }

    /**
    * Sets whether the post type should use the default capabilities or custom capabilities.
    *
    * @param bool $mapMetaCaps If true, the post type will use the default meta capabilities. If false, it will rely on custom capabilities defined in the 'capabilities' argument.
    *
    * @return self
    */
    public function mapMetaCapabilities(bool $mapMetaCaps = true): self {
        $this->args['map_meta_cap'] = $mapMetaCaps;
        return $this;
    }

    /**
    * Sets the supports array for the post type, which determines the features that are enabled for this post type (e.g. editor, thumbnail, custom-fields).
    *
    * @param array $supports An array of features that this post type supports. 
    *                        Common values include 'title', 'editor', 'thumbnail', 'excerpt', 'custom-fields', 'revisions', etc.
    *
    * @return self
    */
    public function supports(array $supports): self {
        $this->args['supports'] = $supports;
        return $this;
    }

    /**
    * Sets the taxonomies that are associated with this post type.
    *
    * @param array $taxonomies An array of taxonomy names (strings) that should be associated with this post type. 
    *                          This allows you to link existing taxonomies to the post type or create new ones.
    *
    * @return self
    */
    public function taxonomies(array $taxonomies): self {
        $this->args['taxonomies'] = $taxonomies;
        return $this;
    }

    /**
    * Sets the rewrite rules for the post type's permalinks.
    *
    * @param array|bool $rewrite An associative array of rewrite rules or false to disable rewrites for this post type. 
    *                            The array can include keys like 'slug', 'with_front', 'pages', and 'feeds' to customize permalink structure.
    *
    * @return self
    */
    public function rewrite(array|bool $rewrite): self {
        $this->args['rewrite'] = $rewrite;
        return $this;
    }

    /**
    * Sets whether the post type should have an archive page.
    *
    * @param bool|string $hasArchive A boolean indicating whether the post type should have an archive page, or a string to specify a custom archive slug.
    * 
    * @return self
    */
    public function hasArchive(bool|string $hasArchive = true): self {
        $this->args['has_archive'] = $hasArchive;
        return $this;
    }

    /**
     * Sets whether the post type should be available for export in the WordPress export tool.
     *
     * @param bool $exportable
     *
     * @return self
     */
    public function exportable(bool $exportable = true): self {
        $this->args['can_export'] = $exportable;
        return $this;
    }

    /**
     * Sets whether the post type should be deleted when its associated user is deleted.
     *
     * @param bool $deleteWithUser
     *
     * @return self
     */
    public function deleteWithUser(bool $deleteWithUser = true): self {
        $this->args['delete_with_user'] = $deleteWithUser;
        return $this;
    }

    /**
     * Sets a custom template for the post type, which can be used to define a default block structure when creating new posts of this type.
     *
     * @param array $template An array of block definitions that represent the default content structure for new posts of this type. 
     *                        Each block definition should include a 'blockName' key for the block type and an optional 'attrs' key for block attributes.
     *
     * @return self
     */
    public function template(array $template): self {
        $this->args['template'] = $template;
        return $this;
    }

    /**
     * Sets the template lock mode for the post type, which controls how the block template can be modified by users.
     *
     * @param string|bool $templateLock A string indicating the template lock mode ('all', 'insert', 'remove') or a boolean (true for 'all', false for no lock).
     *
     * @return self
     */
    public function templateLock(string|bool $templateLock): self {
        $this->args['template_lock'] = $templateLock;
        return $this;
    }

    /**
     * Sets the arguments for registering the post type.
     * 
     * @see https://developer.wordpress.org/reference/functions/register_post_type/
     *
     * @param array $args
     *
     * @return self
     */
    public function args(array $args): self {
        $this->args = array_merge($this->args, $args);
        return $this;
    }

    /***************************
     * Getters
     ***************************/

    /**
     * Retrieves the post type's arguments.
     *
     * @return array
     */
    public function getArgs(): array {
        return $this->args;
    }

    /**
     * Retrieves the field groups associated with this post type.
     *
     * @return array<FieldGroup>
     */
    public function getFieldGroups(): array {
        return $this->fieldGroups;
    }

    /***************************
     * Helpers
     ***************************/

    /**
     * Instantiates the post meta definition if it's provided as a class name.
     *
     * @return void
     */
    protected function instantiatePostMeta(): void {
        if (!is_string($this->meta)) {
            return;
        }

        $this->meta = PostMetaRegister::checkout($this->provider)->makeFrom($this->meta);
    }
}